name: Limpieza Automatica de Logs

on:
  workflow_dispatch: # Mantiene el botón manual por si acaso
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta automáticamente todos los domingos a la medianoche (UTC)

jobs:
  borrar-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Borrar ejecuciones antiguas
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
