name: Ordenar Musica
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Crear Lista JSON Profesional
        run: |
          echo "[" > musica.json
          # Buscamos mp3, obtenemos fecha y nombre completo, ordenamos y generamos JSON
          git ls-files -z *.mp3 | xargs -0 -n1 -I{} git log -1 --format="%at {}" {} | sort -rn | while read line; do
            date=$(echo $line | awk '{print $1}')
            name=$(echo $line | cut -d' ' -f2-)
            echo "{\"name\":\"$name\", \"url\":\"https://raw.githubusercontent.com/angelcrea615-sketch/musica_de_pro_player/main/$name\"}," >> musica.json
          done
          # Quitamos la última coma y cerramos el array
          sed -i '$ s/,$//' musica.json
          echo "]" >> musica.json

      - name: Guardar en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Robot de Orden"
          git add musica.json
          git commit -m "Lista de reproducción actualizada" || exit 0
          git push
