name: Ordenar Musica
on:
  push:
    branches: [ main ] # Se activa al guardar cambios en la rama principal
  workflow_dispatch: # Esto te permite activarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Crear Lista JSON
        run: |
          # Buscamos todos los mp3 en la carpeta principal
          echo "[" > musica.json
          git ls-files -z *.mp3 | xargs -0 -n1 -I{} git log -1 --format="%at {}" {} | sort -rn | awk '{print "{\"name\":\"" $2 "\", \"url\":\"https://raw.githubusercontent.com/angelcrea615-sketch/musica_de_pro_player/main/" $2 "\"},"}' >> musica.json
          # Limpiamos la última coma sobrante
          sed -i '$ s/,$//' musica.json
          echo "]" >> musica.json

      - name: Guardar en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Robot de Orden"
          git add musica.json
          git commit -m "Lista actualizada" || exit 0
          git push
